apiVersion: v2
name: parentchart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: mychart1
  version: "0.1.0"
  repository: "https://stacksimplify.github.io/helm-charts/"
- name: mychart2
  version: "0.4.0"
  repository: "https://stacksimplify.github.io/helm-charts/"
- name: mysql
  version: "9.11.1"
  #version: ">= 9.10.8"
  #version: ">= 9.10.8 < 9.11.0"
  #version: "^9.10.1"  # Downloads 9.11.1 (latest as on today) - deals with major version which is <10
  #version: "~9.10.1"  # Downloads 9.10.10 - that is the latest patch version -  deals with patch version <9.11.0
  #version: "^9.10"    # Downloads 9.11.1 (latest as on today) - deals with major version which is <10
  #version: "~9.10"    # Downloads 9.10.10 - that is the latest patch version -  deals with patch version <9.11.0 
  repository: "https://charts.bitnami.com/bitnami"
  #repository: "@mybitnami1"
  
